export * as trendings from './rest/trendings'
export * as readme from './rest/readme'
export * as auth from './rest/auth'
export * as issues from './rest/issues'
export * as starred from './rest/starred'
export * as repos from './rest/repos'
